#База данных заказов
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  ORDERS_URI: {{ printf "postgres://%s:%s@%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.ordersDbName  | b64enc | quote }}
  BILLING_URI: {{ printf "postgres://%s:%s@%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.billingDbName  | b64enc | quote }}
  STOCK_URI: {{ printf "postgres://%s:%s@%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.stockDbName  | b64enc | quote }}
  DELIVERY_URI: {{ printf "postgres://%s:%s@%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.deliveryDbName  | b64enc | quote }}
---
#Брокер
apiVersion: v1
kind: Secret
metadata:
  name: rabbit-secret
type: Opaque
data:
  RabbitMQ_URI: {{ printf "amqp://%s:%s@%s:5672" .Values.rabbitmq.rabbitmq.username .Values.rabbitmq.rabbitmq.password (include "rabbitmq.fullname" .)  | b64enc | quote}}