{{- if .Values.ingress.enabled -}}
{{- $fullName := include "saga.fullname" . -}}
{{- $stockSvcPort := .Values.stock.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: stock-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
        - path: /stock(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: stock-service
              port:
                number: {{$stockSvcPort}} 
{{- end }}